[params]
currency = "EUR"
currencySymbol = "€"

[module]
[[module.imports]]
  path = "github.com/hugo-fonts/inter"

[outputFormats]
  [outputFormats.HeurekaFeed20]
    baseName = 'heureka-feed'
    mediaType = 'application/xml'

[outputs]
home = ['HTML', 'RSS', 'HeurekaFeed20']
product_alias = ['HTML']

[outputFormats.JS]
mediaType = "text/javascript"
isPlainText = true
